language: android

jdk: oraclejdk8

android:
  components:
  - platform-tools
  - tools
  - android-27
  - build-tools-27.0.3
  - extra-android-m2repository

branches:
  only:
  - master

before_install:
- yes | sdkmanager "platforms;android-27"

install:
  - chmod +x ./gradlew
  - chmod +x ./autobuild/push-apk.sh

script: ./gradlew clean assembleDebug

after_success:
  - ./autobuild/push-apk.sh

notifications:
  email:
    on_success: change
    on_failure: always

env:
  global:
    secure: DIeZaEgUGw95TcFBuk+JiWa8mBJe7ru/p6liE89phuSi6tPXAcd7m5bnEry3qbZl241cg3xEJrrk4s29ejJn5vSI5D+y7uyLRpqFrXoG0kr0AoFSgHZV5n+dEfI8pN1dnmL1Iytr6PCNxYew/L9uEe8uRhyPyRCI4l9geOAO3o1/CTTnRYNKsClRCLMKMAj+5MwKzJGCI0Zs+XXHYcUnHiZxRScxdAVKDwRhowUGtrxSgcjs8lkCFIiP1lWhA/UCQr0PJyPkSl1DHGwW3wM2Ra3kNfzPZFIipwZn9mqlMsfnoEW9TU4ww2nESU1jPtZn9s6+/ZhLI1d79bQnAY57S+AhxkIIVjkH+2bmCz2AdoontLqU0mI8GhtKgX6c+Jnpw5a/1sbE4rOVWN9SDRFCCl8ZpreK9YhG7LeQPO/4BKwVLEc8ddItgeVThg6Kag5gbPOrfyuuNENkp2OeQKEJ45FQvtWc1HpHjUfw84WKmE2vXFQp2CI//FwgTzL5sCAuwHUIhPHsMeL2p9ejuis+HpIOZ5rUkCbX741MoDeou19IdsG2Fr0ZSP/XuEN7iwSRMS7OWErHrqGzuNSGiepieETr/tJYCK68T0OU0ubLsiIpK25v1FSepGjeho4VsBpQChItGzIocnj/Z8zJjOFey23OtDcrI0EfXGDkpohaG6s=
