include: package:pedantic/analysis_options.yaml

analyzer:
  exclude: [build/**]


linter:
  rules:
    prefer_final_fields: true
    prefer_final_locals: true
    omit_local_variable_types: false
    prefer_single_quotes: false
    unnecessary_this: false
    prefer_collection_literals: false
    prefer_if_null_operators: false
    prefer_conditional_assignment: false